replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:989cf449c639285da581399c36e12c83401ad7583dd44231ef1d2b7c95759aa7 
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222
  labels:
    ciliuml2: pool


persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

ssh:
  authorizedKeys: |
    # Place auth keys here ...
    # ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu...


securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
