replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:3c87b57891380491fcb251e01aa86bfbee89b18f09cc003289ccb7df094951c5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault