replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:81c192b30a053c37dfa6217be80aa5076ec35a314b9d3cc5c262928cad7e4578
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault