replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:11aa5c10407d658c55c001ddde9b5f6c778f97c6e86b0f2d2b6a48971cf72cf5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

ssh:
  authorizedKeys: |
    # Place auth keys here ...
    # ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu...
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjYNgOeBJ+f0koBLJg7JzT2U9agAGqd/c1gZbVvCZrK
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
