replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:0579081ba89ffeda377518c26fbf9a6454caec2039a41dc9262372c7dce186f0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault