replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:abac90c428e1056531f6403665a6b5d22c8caa41d897d701d86ddc570fa96a4a 
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault