replicaCount: 1

image:
  repository: ghcr.io/syntax3rror404/k8s-devmachine
  tag: master
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault