replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:9d7bf6ca64f090c46c1bb85fe406a75111ef59207ca6548b72a10f3b5ff3f2a5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault