replicaCount: 1

image:
  repository: ghcr.io/syntax3rror404/k8s-devmachine
  tag: sha256:138df7969731ee1b34b247ff7f49b44d887e6122e7171efb9c75ee509ea013a5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 22

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault