replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:d0917c569a0ac6267cb7bc18a0d950dc97afaaf495f799637394a682be81e95e 
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

ssh:
  authorizedKeys: |
    # Place auth keys here ...
    # ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu...

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault