replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:46b8f94a7fbabde3d205d97517c97bf84e80ef43e6e42c2df27ca276c7269542 
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222
  labels:
    ciliuml2: pool


persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

ssh:
  authorizedKeys: |
    # Place auth keys here ...
    # ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu...


securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
