replicaCount: 1

image:
  source: ghcr.io/syntax3rror404/k8s-devmachine@sha256:b25b3089bece565cf372eb90ac4302db4decbf57af2ee67b6e09df2fa7438d66
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 2222
  targetPort: 2222

persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources: {}

ssh:
  authorizedKeys: |
    # Place auth keys here ...
    # ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu...

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault