apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bashrc
data:
  .bashrc: |
    # ~/.bashrc for dev user
    export PATH="/home/dev/.local/bin:/home/dev/.local/bin/go/bin:$PATH"
    export PYTHONUSERBASE="$HOME/.local"

    # Colors
    export LS_OPTIONS='--color=auto'
    eval "$(dircolors)"
    alias ls='ls $LS_OPTIONS'
    alias ll='ls $LS_OPTIONS -l'
    alias la='ls $LS_OPTIONS -la'

    # Prompt
    PS1='\u@\h:\w\$ '

    # activate venv
    source ~/venv/bin/activate

    # Include local dev bashrc if it exists
    if [ -f ~/.dev_bashrc ]; then
      source ~/.dev_bashrc
    fi