apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoint
data:
  entrypoint.sh: |
    #!/bin/bash

    echo "Ensuring SSH keys directory exists at /home/dev/ssh_keys."
    mkdir -p /home/dev/ssh_keys

    # Generate keys if they do not exist
    if [ ! -f /home/dev/ssh_keys/ssh_host_rsa_key ]; then
        echo "Generating new SSH host RSA key."
        ssh-keygen -t rsa -f /home/dev/ssh_keys/ssh_host_rsa_key -N ''
    fi
    if [ ! -f /home/dev/ssh_keys/ssh_host_ecdsa_key ]; then
        echo "Generating new SSH host ECDSA key."
        ssh-keygen -t ecdsa -f /home/dev/ssh_keys/ssh_host_ecdsa_key -N ''
    fi
    if [ ! -f /home/dev/ssh_keys/ssh_host_ed25519_key ]; then
        echo "Generating new SSH host ED25519 key."
        ssh-keygen -t ed25519 -f /home/dev/ssh_keys/ssh_host_ed25519_key -N ''
    fi

    chmod 600 /home/dev/ssh_keys/ssh_host_*

    echo "Ensuring run directory exists at /home/dev/run."
    mkdir -p /home/dev/run

    echo "Currently running sshd processes:"
    ps aux | grep sshd

    echo "Killing any existing sshd processes..."
    for pid in $(ps aux | grep sshd | grep -v grep | awk '{print $2}'); do
    echo "Killing sshd pid $pid"
    kill $pid
    done

    echo "Removing stale PID file if exists..."
    rm -f /home/dev/run/sshd.pid

    echo "Starting SSH service..."
    exec /usr/sbin/sshd -D -f /etc/ssh/sshd_config \
    -o Port=2222 \
    -o HostKey=/home/dev/ssh_keys/ssh_host_ed25519_key \
    -o HostKey=/home/dev/ssh_keys/ssh_host_rsa_key \
    -o HostKey=/home/dev/ssh_keys/ssh_host_ecdsa_key \
    -o PidFile=/home/dev/run/sshd.pid