apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.source }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        securityContext:
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
            drop:
              {{- toYaml .Values.securityContext.capabilities.drop | nindent 14 }}
          seccompProfile:
            type: {{ .Values.securityContext.seccompProfile.type }}
        volumeMounts:
        - name: home-volume
          mountPath: /home/dev
        - name: entrypoint-script
          mountPath: /usr/local/bin/entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
        - name: ssh-keys
          mountPath: /home/dev/.ssh/authorized_keys
          subPath: authorized_keys
          readOnly: true
        - name: sshd-config-volume
          mountPath: /etc/ssh/sshd_config
          subPath: sshd_config
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: entrypoint-script
        configMap:
          name: {{ .Release.Name }}-entrypoint
          defaultMode: 0755
      - name: home-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      - name: ssh-keys
        configMap:
          name: {{ .Release.Name }}-ssh-keys
          defaultMode: 0755
      - name: sshd-config-volume
        configMap:
          name: {{ .Release.Name }}-sshd-config
          defaultMode: 0755